### ISSUE TITLE
Combine with Source repo?

### ISSUE THREAD

**Issue by whitneyerika** [WWU-IETC-R-Collab/LULC#1]
Hi Skyler,

I'm wondering if it makes sense to condense repositories by topic. I named one "Sources" which has the analysis of Precipitation data, and includes the code to combine precip, lulc, and CEDENSURF data together for next steps. Would you want to move the LULC analysis there?

I only bring in your LULC data output in one place, so it wouldn't be hard to redefine that URL if you do choose to move this content. Let me know what you think!

**Comment by SkylerElmstrom** [comment]
This will probably be beneficial in the long run. Let me wrap up the README and I'll make sure our other links to this source get updated with the new location when we move it.
